### ISSUE TITLE
how can i use it ? 

### ISSUE THREAD

**Issue by SeanBeansShako** [stjeong/KernelMemoryIO#1]
hello i have source code but it's not a compile-to-run source because game limits OpenProcess handle's access to it's .exe so is your kernel device driver can help me to bypass the limitation  ?
sorry i'm noob and don't know what i should do 
thnx

**Comment by stjeong** [comment]
Sorry for that. This device driver just read and write memory (or port) in Kernel space. For example, in 32bit OS, you can read/write memory from 2GB ~ 4GB with this driver.
